### ISSUE TITLE
Repo not updated?

### ISSUE THREAD

**Issue by SuperThinking** [sallar/github-contributions-chart#87]
Guess some updates have been made to GitHub assets but not to this repo. <br/>
-> https://github-contributions.now.sh/<br/>
![image](https://user-images.githubusercontent.com/22829739/97663600-0b345280-1aa0-11eb-95bc-0ba6ac2a2d21.png)
<br/>
`{"date":"2020-05-11","count":12,"color":"var(--color-calendar-graph-day-L2-bg)","intensity":0}`
^ value of color has changed and intensity seems to be 0 for every object

**Comment by x86chi** [comment]
```css
:root, [data-color-mode="light"] {
  --color-calendar-graph-day-bg: #ebedf0;
  --color-calendar-graph-day-L1-bg: #9be9a8;
  --color-calendar-graph-day-L2-bg: #40c463;
  --color-calendar-graph-day-L3-bg: #30a14e;
  --color-calendar-graph-day-L4-bg: #216e39;
}
```

The color injection was changed to CSS variables. [Reference Github asset link](https://github.githubassets.com/assets/frameworks-ade8c0b2824918a1541c3ba74047219e.css)

```css
:root {
  --color-calendar-graph-day-border: rgba(27, 31, 35, 0.06);
}

.calendar-graph rect.day {
  shape-rendering: geometricPrecision;
  outline: 1px solid var(--color-calendar-graph-day-border);
  outline-offset: -1px;
}
```

By the way, The newly added outline style doen't seem added.
